
#name: Vsv-glass
description: Engineering and Reverse-engineering solutions
url: https://vsv-glass.ru
#repository: https://github.com/megavad/vsv-glass.git
#baseurl: /
timezone: Russian Federation/Moscow
twitter:
  username: Vadim
logo: '/img/logo.png'
google_analytics_id: UA-0000000-1
google_site_verification: to_be_done
#cloudinary_url: https://res.cloudinary.ddd/jekyll/image/upload/f_auto,q_auto,w_404
collections:
  projs:
    permalink: "/:collection/:path/"
    #permalink: "/projs/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _projs
    type: projs
  values:
    layout: desc
- scope:
    path: _docs
    type: docs
  values:
    layout: desc
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
- scope:
    path: ''
  values:
    layout: desc
future: true
#plugins:
#- jekyll-avatar
#- jekyll-feed
#- jekyll-mentions
#- jekyll-redirect-from
#- jekyll-seo-tag
#- jekyll-sitemap
#- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- icomoon-selection.json
- readme.md
